# Generated by Django 4.2.20 on 2025-04-03 13:55

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumb': {'crop': 'smart', 'height': 300, 'width': 300}}, verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
